extends Node3D
## Scatters trees and rocks over the island's dry land.
##
## Scenery is drawn with MultiMesh and carries no physics body — a body is
## promoted only when something actually picks the object up. That keeps a few
## hundred props at one batch per prop type; a batch costs one draw call per
## material slot in its mesh, so five in total for the generated meshes.
##
## Trees used to be a trunk MultiMesh plus a canopy MultiMesh sharing an instance
## index, because a tree needs two colours and an engine primitive carries one.
## tree.glb is a single joined mesh with a slot for bark and two for foliage, so
## the pairing and the paired-index bookkeeping are gone: one MultiMesh per type.
##
## Per-instance variety is scale and yaw only. MultiMesh instance colours were
## considered and dropped: an instance colour only reaches albedo when the
## material sets vertex_color_use_as_albedo, which the imported glTF materials do
## not, and setting it on every surface would wash one tint over bark and foliage
## alike — the meshes already carry deliberate per-part colours.
##
## This node keeps its own authoritative copy of every instance transform and
## treats the MultiMesh as write-only. Two reasons: reading transforms back out
## of the rendering server is a stall, and under `--headless` the dummy renderer
## discards the data entirely, so `get_instance_transform` returns identity and
## nothing about placement could be tested.

const RNG_STREAM := &"world"
const TYPE_TREE := &"tree"
const TYPE_ROCK := &"rock"
## Generated by tools/blender/generate_meshes.py, and optional: a checkout
## without them falls back to the engine primitives at the bottom of this file.
const TREE_SCENE := "res://assets/procedural/meshes/tree.glb"
const ROCK_SCENE := "res://assets/procedural/meshes/rock.glb"
## Scale applied to an instance to make it vanish while it is being carried.
const HIDDEN_SCALE := Vector3(0.0001, 0.0001, 0.0001)
## Per-instance scale spread, as (min, max), so a forest is not stamped from one
## tree. Uniform across all three axes: a non-uniform scale composed with the
## yaw shears the basis, and then get_scale() — which is what the hand sizes a
## grabbed prop's collision box from — stops describing what is drawn.
const TREE_SCALE := Vector2(0.75, 1.45)
const ROCK_SCALE := Vector2(0.55, 1.6)
## Fallback extents for a type this node never placed. A grabbed villager reaches
## detached_extents, and a shapeless box is better than a zero-sized one.
const UNKNOWN_EXTENTS := Vector3(0.8, 0.7, 0.8)

@export var tree_count: int = 200
@export var rock_count: int = 80
## Trees avoid the tideline and the bare peaks.
@export var tree_min_height: float = 1.5
@export var tree_max_height: float = 15.0
@export var rock_min_height: float = 0.3
@export var rock_max_height: float = 22.0
@export var placement_attempts_per_item: int = 24

# One MultiMesh per prop type, plus the transform that type's mesh carries inside
# its .glb (see _resolve_mesh), which every instance is composed with on the way
# to the rendering server.
var _prop_node: Dictionary[StringName, MultiMeshInstance3D] = {}
var _prop_local: Dictionary[StringName, Transform3D] = {}

# Authoritative state, keyed by WorldObject id.
var _body_rest: Dictionary[int, Transform3D] = {}
var _hidden: Dictionary[int, bool] = {}


## Fills the island with scenery and registers every piece in the world store.
func populate(island: Node3D, registry: Node) -> void:
	var rng := RandomNumberGenerator.new()
	rng.seed = _seed()

	var tree_spots: Array[Vector3] = _pick_spots(
		island, rng, tree_count, tree_min_height, tree_max_height
	)
	var rock_spots: Array[Vector3] = _pick_spots(
		island, rng, rock_count, rock_min_height, rock_max_height
	)

	_prop_node[TYPE_TREE] = _make_multimesh(
		"Trees", _resolve_mesh(TYPE_TREE, TREE_SCENE, _trunk_mesh()), tree_spots.size()
	)
	_prop_node[TYPE_ROCK] = _make_multimesh(
		"Rocks", _resolve_mesh(TYPE_ROCK, ROCK_SCENE, _rock_mesh()), rock_spots.size()
	)

	for i in tree_spots.size():
		var tree: WorldObject = registry.add(TYPE_TREE, tree_spots[i], null, i)
		_place(tree, tree_spots[i], TREE_SCALE, rng)

	for i in rock_spots.size():
		var rock: WorldObject = registry.add(TYPE_ROCK, rock_spots[i], null, i)
		_place(rock, rock_spots[i], ROCK_SCALE, rng)


## Hides an object's instance because something has picked it up.
func hide_instance(object: WorldObject) -> void:
	if not _body_rest.has(object.id):
		return
	_hidden[object.id] = true
	_push(object)


## Puts an object back into the MultiMesh at a new resting place.
func restore_instance(object: WorldObject, at: Vector3) -> void:
	if not _body_rest.has(object.id):
		return
	_body_rest[object.id] = Transform3D(_body_rest[object.id].basis, at)
	_hidden[object.id] = false
	object.position = at
	_push(object)


## True while this object is being carried rather than drawn in place.
func is_hidden(object: WorldObject) -> bool:
	return _hidden.get(object.id, false)


## The transform this object is currently drawn with — authoritative, and safe
## to assert against in headless tests.
func visual_transform(object: WorldObject) -> Transform3D:
	var rest: Transform3D = _body_rest.get(object.id, Transform3D.IDENTITY)
	if _hidden.get(object.id, false):
		return Transform3D(rest.basis.orthonormalized().scaled(HIDDEN_SCALE), rest.origin)
	return rest


func rest_transform_of(object: WorldObject) -> Transform3D:
	return _body_rest.get(object.id, Transform3D.IDENTITY)


## Half-extents of a box bounding this prop, for the physics proxy the hand makes.
##
## The hand doubles this for the box size and lifts the shape by extents.y, which
## is what a mesh standing on y = 0 needs. Measured off the mesh rather than
## written down, so it cannot drift from whatever Blender last produced.
func detached_extents(object: WorldObject) -> Vector3:
	var type: StringName = _visual_type(object)
	var mesh: Mesh = _mesh_of(type)
	if mesh == null:
		return UNKNOWN_EXTENTS
	var local: Transform3D = _prop_local.get(type, Transform3D.IDENTITY)
	var scale: Vector3 = _body_rest.get(object.id, Transform3D.IDENTITY).basis.get_scale()
	return (local * mesh.get_aabb()).size * scale * 0.5


## Visual for a detached, physically simulated copy of this prop — the same mesh
## at the same size as the instance that was standing there a moment ago.
##
## Yaw is dropped: the body takes its orientation from physics the instant it is
## thrown, so the resting yaw would only be a frame of stale rotation.
func build_detached_visual(object: WorldObject) -> Node3D:
	var holder := Node3D.new()
	var type: StringName = _visual_type(object)
	var scale: Vector3 = _body_rest.get(object.id, Transform3D.IDENTITY).basis.get_scale()
	var visual := MeshInstance3D.new()
	visual.mesh = _mesh_of(type)
	visual.transform = (
		Transform3D(Basis.from_scale(scale), Vector3.ZERO)
		* _prop_local.get(type, Transform3D.IDENTITY)
	)
	holder.add_child(visual)
	return holder


## Writes this object's current transform into the rendering server.
##
## Deliberately routed through visual_transform(), the same function the tests
## assert against, so what is drawn and what is claimed cannot diverge.
func _push(object: WorldObject) -> void:
	var instance: MultiMeshInstance3D = _prop_node.get(object.type)
	if not _instance_valid(instance, object.multimesh_index):
		return
	var local: Transform3D = _prop_local.get(object.type, Transform3D.IDENTITY)
	instance.multimesh.set_instance_transform(
		object.multimesh_index, visual_transform(object) * local
	)


func _instance_valid(instance: MultiMeshInstance3D, index: int) -> bool:
	return (
		instance != null
		and instance.multimesh != null
		and index >= 0
		and index < instance.multimesh.instance_count
	)


## Records an instance's resting transform and draws it.
##
## No vertical lift: the generated meshes stand on y = 0, so the placement point
## is the ground point. (The primitive fallbacks are centred on their origin and
## so sit half-buried, which is the least of a missing-asset checkout's worries.)
func _place(
	object: WorldObject, at: Vector3, scale_range: Vector2, rng: RandomNumberGenerator
) -> void:
	var scale: float = rng.randf_range(scale_range.x, scale_range.y)
	var yaw: float = rng.randf_range(0.0, TAU)
	_body_rest[object.id] = Transform3D(Basis(Vector3.UP, yaw).scaled(Vector3.ONE * scale), at)
	_hidden[object.id] = false
	_push(object)


## The prop type whose mesh stands in for this object. Types this node never
## placed — a grabbed villager has no scatter instance — are drawn as rocks,
## which is what the hand has always built for them.
func _visual_type(object: WorldObject) -> StringName:
	return object.type if _prop_node.has(object.type) else TYPE_ROCK


func _mesh_of(type: StringName) -> Mesh:
	var instance: MultiMeshInstance3D = _prop_node.get(type)
	if instance == null or instance.multimesh == null:
		return null
	return instance.multimesh.mesh


func _pick_spots(
	island: Node3D, rng: RandomNumberGenerator, wanted: int, min_h: float, max_h: float
) -> Array[Vector3]:
	var spots: Array[Vector3] = []
	var half: float = island.extent * 0.5 * 0.94
	for i in wanted:
		for attempt in placement_attempts_per_item:
			var x: float = rng.randf_range(-half, half)
			var z: float = rng.randf_range(-half, half)
			var h: float = island.height_at(x, z)
			if h >= min_h and h <= max_h:
				spots.append(Vector3(x, h, z))
				break
	return spots


func _make_multimesh(node_name: String, mesh: Mesh, instances: int) -> MultiMeshInstance3D:
	var multimesh := MultiMesh.new()
	# transform_format must be set while instance_count is still 0; the engine
	# refuses the change afterwards and silently leaves the mesh in 2D mode.
	multimesh.transform_format = MultiMesh.TRANSFORM_3D
	multimesh.mesh = mesh
	multimesh.instance_count = instances
	var instance := MultiMeshInstance3D.new()
	instance.name = node_name
	instance.multimesh = multimesh
	# No material_override: it would flatten the mesh's several material slots
	# into one colour. The primitives carry their colour on the mesh instead.
	add_child(instance)
	return instance


## The mesh a prop type is drawn with, plus the transform it needs.
##
## A .glb cannot be load()ed as a Mesh: it imports as a scene holding one
## MeshInstance3D with a material slot per part, so the Mesh has to be lifted out
## of an instance. The exporter also leaves the model's placement on the glTF
## node rather than in the vertex data — tree.glb's node raises the mesh 1.5 m
## and rock.glb's also scales it — so that transform is recorded and folded into
## every instance. Taking .mesh alone draws a sunken tree and a misshapen rock.
##
## Returns `primitive` when the asset is absent, so a checkout without the
## generated meshes still runs.
func _resolve_mesh(type: StringName, path: String, primitive: Mesh) -> Mesh:
	_prop_local[type] = Transform3D.IDENTITY
	if not ResourceLoader.exists(path):
		return primitive
	var packed: PackedScene = load(path)
	if packed == null:
		return primitive

	var root: Node = packed.instantiate()
	if root == null:
		return primitive
	var found: MeshInstance3D = _first_mesh_instance(root)
	var mesh: Mesh = null
	if found != null and found.mesh != null:
		mesh = found.mesh
		_prop_local[type] = _transform_in_scene(found)
	# Freed at once: only the Mesh resource is wanted, and it is reference
	# counted so it outlives the node. An off-tree node left alive here would be
	# reported as a leak by the test runner.
	root.free()

	if mesh == null:
		return primitive
	return mesh


func _first_mesh_instance(node: Node) -> MeshInstance3D:
	if node is MeshInstance3D:
		return node as MeshInstance3D
	for child: Node in node.get_children():
		var found: MeshInstance3D = _first_mesh_instance(child)
		if found != null:
			return found
	return null


## A node's transform relative to the scene it was instantiated from.
##
## Accumulated by hand rather than read from global_transform, because the scene
## is never added to the tree and Node3D raises an error when asked for a global
## transform off-tree.
func _transform_in_scene(node: Node3D) -> Transform3D:
	var result := Transform3D.IDENTITY
	var current: Node3D = node
	while current != null:
		result = current.transform * result
		current = current.get_parent() as Node3D
	return result


## Fallback trunk, drawn only when tree.glb is missing. A bare cylinder is a poor
## tree, but a missing asset should degrade rather than crash.
func _trunk_mesh() -> Mesh:
	var mesh := CylinderMesh.new()
	mesh.top_radius = 0.18
	mesh.bottom_radius = 0.3
	mesh.height = 1.0
	mesh.radial_segments = 6
	mesh.rings = 1
	mesh.material = _colour_material(Color(0.32, 0.22, 0.14))
	return mesh


## Fallback canopy, currently unreferenced: a MultiMesh takes one mesh, so the
## fallback tree is the trunk alone. Kept because it is the other half of the
## primitive pair and costs nothing; delete it freely if the fallback is dropped.
func _canopy_mesh() -> Mesh:
	var mesh := SphereMesh.new()
	mesh.radius = 1.0
	mesh.height = 2.0
	mesh.radial_segments = 7
	mesh.rings = 4
	mesh.material = _colour_material(Color(0.20, 0.42, 0.18))
	return mesh


## Fallback boulder, drawn only when rock.glb is missing.
func _rock_mesh() -> Mesh:
	var mesh := SphereMesh.new()
	mesh.radius = 0.8
	mesh.height = 1.4
	mesh.radial_segments = 6
	mesh.rings = 3
	mesh.material = _colour_material(Color(0.48, 0.47, 0.45))
	return mesh


func _colour_material(colour: Color) -> StandardMaterial3D:
	var material := StandardMaterial3D.new()
	material.albedo_color = colour
	material.roughness = 0.9
	material.specular_mode = BaseMaterial3D.SPECULAR_DISABLED
	return material


func _seed() -> int:
	if is_inside_tree():
		var rng_service: Node = get_node_or_null(^"/root/Rng")
		if rng_service != null:
			return rng_service.derive_seed(RNG_STREAM)
	return hash("numen:scatter")
