"""Generates NUMEN's static world meshes and exports them as glTF.

Run headless, from the repo root:

    blender --background --factory-startup --python tools/blender/generate_meshes.py

Output goes to assets/procedural/meshes/*.glb. Those files are committed: they are
generated by this script from primitives and carry no third-party content, so they
are licence-clean by construction and need no ATTRIBUTIONS.md entry. Regenerate
them by re-running this script rather than editing the .glb.

Why Blender rather than more GDScript primitives: the village was built from
BoxMesh cubes and CapsuleMesh villagers, which read as placeholder blocks at any
camera distance. A pitched roof, a doorway and a stepped temple base are trivial
here and impossible to express as a single Godot primitive.

Everything is modelled base-at-Z=0 and centred on the origin in X/Y. Blender is
Z-up and glTF is Y-up; the exporter converts, so a mesh built sitting on the
Blender floor arrives in Godot sitting on the ground plane at y=0. That means the
caller places it at terrain height with NO half-height lift, unlike the engine
primitives it replaces.
"""

import math
import os
import sys

import bpy

# Deterministic by construction: no randomness anywhere in this file. Variation
# between instances is applied in-engine by the scatter, which owns its own seeded
# generator, so two runs of this script produce byte-comparable meshes.

OUT_DIR = os.path.join("assets", "procedural", "meshes")

THATCH = (0.42, 0.30, 0.13)
TIMBER = (0.30, 0.20, 0.12)
PLASTER = (0.68, 0.62, 0.50)
STONE = (0.44, 0.43, 0.41)
STONE_DARK = (0.32, 0.31, 0.30)
GOLD = (0.62, 0.48, 0.16)
BARK = (0.28, 0.19, 0.12)
LEAF = (0.20, 0.40, 0.16)
LEAF_LIGHT = (0.26, 0.47, 0.19)
SOIL = (0.28, 0.20, 0.13)
WHEAT = (0.72, 0.60, 0.24)
CLOTH = (0.55, 0.42, 0.32)
SKIN = (0.72, 0.56, 0.44)


def clear_scene() -> None:
    """Empties the scene without touching user preferences."""
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for block in (bpy.data.meshes, bpy.data.materials, bpy.data.objects):
        for item in list(block):
            if item.users == 0:
                block.remove(item)


def material(name: str, rgb: tuple, roughness: float = 0.9) -> bpy.types.Material:
    existing = bpy.data.materials.get(name)
    if existing is not None:
        return existing
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    # Only Base Color / Roughness / Metallic are touched: those three input names
    # have been stable across Blender 4.x and 5.x, whereas the specular inputs
    # were renamed and would break this script on a version bump.
    bsdf.inputs["Base Color"].default_value = (rgb[0], rgb[1], rgb[2], 1.0)
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["Metallic"].default_value = 0.0
    return mat


def _finish(obj, mat, loc, rot=(0.0, 0.0, 0.0)):
    obj.data.materials.append(mat)
    obj.location = loc
    obj.rotation_euler = rot
    return obj


def box(size, loc, mat, rot=(0.0, 0.0, 0.0)):
    """An axis-aligned box of the given full size, centred on `loc`."""
    bpy.ops.mesh.primitive_cube_add(size=2.0)
    obj = bpy.context.active_object
    obj.scale = (size[0] * 0.5, size[1] * 0.5, size[2] * 0.5)
    return _finish(obj, mat, loc, rot)


def cyl(radius, depth, loc, mat, verts=8, rot=(0.0, 0.0, 0.0)):
    bpy.ops.mesh.primitive_cylinder_add(radius=radius, depth=depth, vertices=verts)
    return _finish(bpy.context.active_object, mat, loc, rot)


def cone(radius, depth, loc, mat, verts=8, rot=(0.0, 0.0, 0.0), radius2=0.0):
    bpy.ops.mesh.primitive_cone_add(
        radius1=radius, radius2=radius2, depth=depth, vertices=verts
    )
    return _finish(bpy.context.active_object, mat, loc, rot)


def sphere(radius, loc, mat, segments=10, rings=6, scale=(1.0, 1.0, 1.0)):
    bpy.ops.mesh.primitive_ico_sphere_add(radius=radius, subdivisions=1)
    obj = bpy.context.active_object
    obj.scale = scale
    return _finish(obj, mat, loc)


def export(name: str, objects: list) -> str:
    """Joins the objects into one mesh and writes assets/procedural/meshes/<name>.glb.

    Joined rather than exported as a hierarchy so each building is a single
    MeshInstance3D in Godot. A village of thirty huts as thirty nodes each with
    five children is thirty times the scene-tree cost for no visual gain; joining
    keeps the material slots, which glTF carries as separate primitives and Godot
    reads back as surfaces on one mesh.
    """
    bpy.ops.object.select_all(action="DESELECT")
    for obj in objects:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = objects[0]
    if len(objects) > 1:
        bpy.ops.object.join()
    joined = bpy.context.active_object
    joined.name = name

    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, "%s.glb" % name)
    bpy.ops.export_scene.gltf(
        filepath=os.path.abspath(path),
        export_format="GLB",
        use_selection=True,
        export_apply=True,
        export_yup=True,
    )
    print("WROTE %s" % path)
    bpy.ops.object.select_all(action="DESELECT")
    joined.select_set(True)
    bpy.ops.object.delete()
    return path


# --- the meshes ---------------------------------------------------------------

def build_hut() -> list:
    """A villager's house: plastered walls, timber corner posts, thatched roof."""
    wall = material("plaster", PLASTER)
    thatch = material("thatch", THATCH, roughness=0.95)
    timber = material("timber", TIMBER)

    parts = [
        box((2.6, 2.6, 1.7), (0.0, 0.0, 0.85), wall),
        # Pitched roof as a four-sided cone, overhanging the walls so the
        # silhouette reads as a roof rather than a lid.
        cone(2.35, 1.5, (0.0, 0.0, 2.45), thatch, verts=4, rot=(0.0, 0.0, math.pi / 4)),
        box((0.7, 0.12, 1.15), (0.0, -1.32, 0.575), timber),
    ]
    for x in (-1.25, 1.25):
        for y in (-1.25, 1.25):
            parts.append(box((0.18, 0.18, 1.75), (x, y, 0.875), timber))
    return parts


def build_storehouse() -> list:
    """Bigger than a hut, raised on stilts, with sacks visible under the eaves."""
    wall = material("plaster", PLASTER)
    thatch = material("thatch", THATCH, roughness=0.95)
    timber = material("timber", TIMBER)
    grain = material("wheat", WHEAT)

    parts = [
        box((4.0, 3.2, 0.25), (0.0, 0.0, 0.4), timber),
        box((3.6, 2.9, 2.0), (0.0, 0.0, 1.5), wall),
        cone(3.3, 1.7, (0.0, 0.0, 3.35), thatch, verts=4, rot=(0.0, 0.0, math.pi / 4)),
    ]
    for x in (-1.7, 1.7):
        for y in (-1.35, 1.35):
            parts.append(cyl(0.14, 0.6, (x, y, 0.3), timber, verts=6))
    for i, x in enumerate((-1.0, -0.2, 0.6)):
        parts.append(sphere(0.34, (x, -1.75, 0.78), grain, scale=(1.0, 1.0, 1.15)))
    return parts


def build_temple() -> list:
    """The village centre: a stepped stone plinth, columns, and a gilded altar."""
    stone = material("stone", STONE)
    dark = material("stone_dark", STONE_DARK)
    gold = material("gold", GOLD, roughness=0.35)

    parts = [
        box((5.4, 5.4, 0.35), (0.0, 0.0, 0.175), stone),
        box((4.6, 4.6, 0.32), (0.0, 0.0, 0.51), stone),
        box((3.8, 3.8, 0.3), (0.0, 0.0, 0.82), dark),
        box((4.4, 4.4, 0.35), (0.0, 0.0, 3.2), stone),
        cone(3.1, 1.1, (0.0, 0.0, 3.92), dark, verts=4, rot=(0.0, 0.0, math.pi / 4)),
        cyl(0.5, 0.9, (0.0, 0.0, 1.42), gold, verts=8),
        sphere(0.42, (0.0, 0.0, 2.15), gold, scale=(1.0, 1.0, 0.8)),
    ]
    for x in (-1.6, 1.6):
        for y in (-1.6, 1.6):
            parts.append(cyl(0.26, 2.05, (x, y, 2.0), stone, verts=8))
    return parts


def build_field() -> list:
    """Tilled soil with rows of wheat, so a field reads as farmed ground."""
    soil = material("soil", SOIL)
    wheat = material("wheat", WHEAT)

    parts = [box((6.0, 6.0, 0.12), (0.0, 0.0, 0.06), soil)]
    # Six furrows of five sheaves. Enough to read as a crop from the gameplay
    # camera without turning one field into hundreds of triangles.
    for row in range(6):
        y = -2.5 + row * 1.0
        for col in range(5):
            x = -2.0 + col * 1.0
            parts.append(cone(0.20, 0.75, (x, y, 0.5), wheat, verts=5, radius2=0.06))
    return parts


def build_tree() -> list:
    """A tapered trunk with two branch stubs and three canopy tiers."""
    bark = material("bark", BARK)
    leaf = material("leaf", LEAF)
    leaf_light = material("leaf_light", LEAF_LIGHT)

    return [
        cone(0.30, 3.0, (0.0, 0.0, 1.5), bark, verts=7, radius2=0.17),
        cyl(0.10, 0.9, (0.32, 0.0, 2.1), bark, verts=5, rot=(0.0, math.pi / 3.4, 0.0)),
        cyl(0.10, 0.8, (-0.28, 0.1, 2.4), bark, verts=5, rot=(0.0, -math.pi / 3.2, 0.0)),
        sphere(1.30, (0.0, 0.0, 3.35), leaf, scale=(1.0, 1.0, 0.80)),
        sphere(1.00, (0.30, 0.18, 4.05), leaf_light, scale=(1.0, 1.0, 0.85)),
        sphere(0.78, (-0.30, -0.15, 4.45), leaf, scale=(1.0, 1.0, 0.9)),
    ]


def build_rock() -> list:
    """A faceted boulder with two smaller shoulders, so it is not a lone sphere."""
    stone = material("stone", STONE)
    dark = material("stone_dark", STONE_DARK)
    return [
        sphere(0.85, (0.0, 0.0, 0.55), stone, scale=(1.15, 0.95, 0.72)),
        sphere(0.42, (0.55, 0.28, 0.28), dark, scale=(1.0, 0.85, 0.7)),
        sphere(0.33, (-0.48, -0.22, 0.24), stone, scale=(0.95, 1.0, 0.65)),
    ]


def build_villager() -> list:
    """A low-poly humanoid, replacing the bare capsule.

    Not rigged: villagers slide to their targets and are only ever seen from the
    gameplay camera, so a rig would cost import complexity for motion nobody can
    resolve at that distance. The engine bobs and turns it instead.
    """
    cloth = material("cloth", CLOTH)
    skin = material("skin", SKIN)
    timber = material("timber", TIMBER)

    parts = [
        cone(0.30, 0.95, (0.0, 0.0, 0.475), cloth, verts=7, radius2=0.20),
        box((0.42, 0.26, 0.44), (0.0, 0.0, 1.14), cloth),
        sphere(0.19, (0.0, 0.0, 1.52), skin, scale=(1.0, 1.05, 1.1)),
        cyl(0.06, 0.5, (0.26, 0.0, 1.12), skin, verts=5, rot=(0.0, 0.22, 0.0)),
        cyl(0.06, 0.5, (-0.26, 0.0, 1.12), skin, verts=5, rot=(0.0, -0.22, 0.0)),
        box((0.34, 0.30, 0.10), (0.0, 0.02, 1.66), timber),
    ]
    return parts


BUILDERS = {
    "hut": build_hut,
    "storehouse": build_storehouse,
    "temple": build_temple,
    "field": build_field,
    "tree": build_tree,
    "rock": build_rock,
    "villager": build_villager,
}


def main() -> int:
    written = []
    for name, builder in BUILDERS.items():
        clear_scene()
        written.append(export(name, builder()))
    print("GENERATED %d meshes" % len(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
