"""Generates NUMEN's miracle VFX particle meshes and exports them as glTF.

Run headless, from the repo root:

    blender --background --factory-startup --python tools/blender/generate_vfx.py

Output goes to assets/procedural/meshes/vfx_*.glb. Those files are committed:
they are generated by this script from primitives and carry no third-party
content, so they are licence-clean by construction and need no ATTRIBUTIONS.md
entry. Regenerate them by re-running this script rather than editing the .glb.

These are particle meshes: each one is drawn dozens of times per cast by a
GPUParticles3D draw pass, so every model here is tiny and as low-poly as it can
be while still reading as its thing in flight. The in-engine effect overrides
the material anyway (particle colour ramps only reach albedo through
vertex_color_use_as_albedo, which imported glTF materials do not set), so the
materials here exist for the contact-sheet eyeball, not for the game.

Convention deviation from generate_meshes.py, on purpose: particles are centred
on the origin rather than base-at-Z=0, because they tumble in flight and must
rotate about their middle, not orbit a corner. The one exception is
vfx_bolt_segment, which IS base-at-Z=0 so the runtime can stack segments into a
bolt by walking a height cursor.

Unlike the world meshes, transforms are APPLIED before export. The runtime
lifts the bare Mesh resource out of the .glb and hands it to a particle draw
pass, where any transform left on the glTF node would simply be lost — scatter's
_prop_local dance exists to fold that transform back in, and particles have no
equivalent hook.
"""

import math
import os
import sys

import bpy

# Deterministic by construction: no randomness anywhere in this file. The
# lightning bolt's jaggedness is applied in-engine by stacking segments with a
# seeded RNG, so two runs of this script produce byte-comparable meshes.

OUT_DIR = os.path.join("assets", "procedural", "meshes")

GRAIN_GOLD = (0.78, 0.58, 0.18)
LEAF_GREEN = (0.22, 0.45, 0.16)
DROP_BLUE = (0.25, 0.50, 0.85)
PUFF_WHITE = (0.92, 0.92, 0.94)
BOLT_PALE = (0.95, 0.93, 0.75)
MOTE_GOLD = (0.95, 0.85, 0.55)


def clear_scene() -> None:
    """Empties the scene without touching user preferences."""
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for block in (bpy.data.meshes, bpy.data.materials, bpy.data.objects):
        for item in list(block):
            if item.users == 0:
                block.remove(item)


def material(name: str, rgb: tuple, roughness: float = 0.9) -> bpy.types.Material:
    existing = bpy.data.materials.get(name)
    if existing is not None:
        return existing
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    # Only Base Color / Roughness / Metallic are touched: those three input names
    # have been stable across Blender 4.x and 5.x, whereas the specular inputs
    # were renamed and would break this script on a version bump.
    bsdf.inputs["Base Color"].default_value = (rgb[0], rgb[1], rgb[2], 1.0)
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["Metallic"].default_value = 0.0
    return mat


def _finish(obj, mat, loc, rot=(0.0, 0.0, 0.0)):
    obj.data.materials.append(mat)
    obj.location = loc
    obj.rotation_euler = rot
    return obj


def cone(radius, depth, loc, mat, verts=8, rot=(0.0, 0.0, 0.0), radius2=0.0):
    bpy.ops.mesh.primitive_cone_add(
        radius1=radius, radius2=radius2, depth=depth, vertices=verts
    )
    return _finish(bpy.context.active_object, mat, loc, rot)


def sphere(radius, loc, mat, scale=(1.0, 1.0, 1.0)):
    bpy.ops.mesh.primitive_ico_sphere_add(radius=radius, subdivisions=1)
    obj = bpy.context.active_object
    obj.scale = scale
    return _finish(obj, mat, loc)


def diamond(name, size, loc, mat, scale=(1.0, 1.0, 1.0)):
    """A six-vertex octahedron, built from data because Blender has no primitive
    for it and an icosphere's 42 vertices is seven times the budget a mote needs."""
    s = size
    verts = [(s, 0, 0), (-s, 0, 0), (0, s, 0), (0, -s, 0), (0, 0, s), (0, 0, -s)]
    faces = [
        (0, 2, 4), (2, 1, 4), (1, 3, 4), (3, 0, 4),
        (2, 0, 5), (1, 2, 5), (3, 1, 5), (0, 3, 5),
    ]
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(verts, [], faces)
    mesh.validate()
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    obj.scale = scale
    return _finish(obj, mat, loc)


def export(name: str, objects: list) -> str:
    """Joins the objects into one mesh, applies transforms, and writes
    assets/procedural/meshes/<name>.glb.

    Transforms are applied because the runtime hands the bare Mesh to a particle
    draw pass, which has nowhere to put a node transform — a scale left on the
    object would silently vanish and every particle would come out unit-sized.
    """
    bpy.ops.object.select_all(action="DESELECT")
    for obj in objects:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = objects[0]
    if len(objects) > 1:
        bpy.ops.object.join()
    joined = bpy.context.active_object
    joined.name = name
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)

    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, "%s.glb" % name)
    bpy.ops.export_scene.gltf(
        filepath=os.path.abspath(path),
        export_format="GLB",
        use_selection=True,
        export_apply=True,
        export_yup=True,
    )
    print("WROTE %s" % path)
    bpy.ops.object.select_all(action="DESELECT")
    joined.select_set(True)
    bpy.ops.object.delete()
    return path


# --- the meshes ---------------------------------------------------------------

def build_grain() -> list:
    """A wheat kernel: an icosphere stretched along its length. Fountains out of
    the food miracle by the dozen."""
    return [sphere(0.05, (0.0, 0.0, 0.0), material("vfx_grain", GRAIN_GOLD, 0.7),
                   scale=(0.6, 0.6, 1.7))]


def build_leaf() -> list:
    """A single leaf: the octahedron flattened to a blade and stretched long, so
    it glints as it tumbles instead of reading as a dot."""
    return [diamond("leaf_shape", 0.1, (0.0, 0.0, 0.0),
                    material("vfx_leaf", LEAF_GREEN, 0.8),
                    scale=(0.55, 1.0, 0.12))]


def build_droplet() -> list:
    """A water drop: sphere body, cone tail pointing up, the way a drop actually
    falls."""
    blue = material("vfx_droplet", DROP_BLUE, 0.15)
    return [
        sphere(0.035, (0.0, 0.0, 0.0), blue),
        cone(0.03, 0.07, (0.0, 0.0, 0.045), blue, verts=6),
    ]


def build_puff() -> list:
    """A cloud puff, squashed so a clump of them reads as vapour, not as balls."""
    return [sphere(0.09, (0.0, 0.0, 0.0), material("vfx_puff", PUFF_WHITE, 1.0),
                   scale=(1.0, 1.0, 0.6))]


def build_bolt_segment() -> list:
    """A short jagged prism for the lightning bolt.

    Base at Z=0, top at Z=0.8 — the one base-anchored mesh here, because the
    runtime stacks these with a rising height cursor. The main shaft is a tapered
    triangular prism and a thin side spur juts off at an angle; stacked with
    random yaw per segment, the spurs are what makes the bolt read as jagged
    rather than as a straight glowing pole.
    """
    pale = material("vfx_bolt", BOLT_PALE, 0.4)
    return [
        cone(0.05, 0.8, (0.0, 0.0, 0.4), pale, verts=3, radius2=0.032),
        cone(0.022, 0.34, (0.05, 0.0, 0.42), pale, verts=3,
             rot=(0.0, math.radians(38.0), 0.0)),
    ]


def build_mote() -> list:
    """A tiny six-vertex diamond for heal sparkles, slightly elongated so it has
    a facet to catch the glow from any angle."""
    return [diamond("mote_shape", 0.045, (0.0, 0.0, 0.0),
                    material("vfx_mote", MOTE_GOLD, 0.4),
                    scale=(0.7, 0.7, 1.3))]


BUILDERS = {
    "vfx_grain": build_grain,
    "vfx_leaf": build_leaf,
    "vfx_droplet": build_droplet,
    "vfx_puff": build_puff,
    "vfx_bolt_segment": build_bolt_segment,
    "vfx_mote": build_mote,
}


def main() -> int:
    written = []
    for name, builder in BUILDERS.items():
        clear_scene()
        written.append(export(name, builder()))
    print("GENERATED %d meshes" % len(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
